name: 'Update service image actions'
description: 'Update service image actions'
inputs:
  service:
    required: true
  gh-token:
    description: 'GitHub Token'
    required: true
  deployments-repository:
    required: true
  target-path:
    required: true
  yq-image-path:
    required: true
  image-version:
    required: true
  commit-message:
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: time sleep $((RANDOM % 20))
      shell: bash
    - name: Checkout deployments repository
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.deployments-repository }}
        ref: main
        path: service-image-update-checkout
        token: ${{ inputs.gh-token }}

    - name: Update image value
      run: |
        cd service-image-update-checkout
        yq -i '${{ inputs.yq-image-path }}="${{ inputs.image-version }}"' ${{ inputs.target-path }}
      shell: bash        
    - name: Commit version file
      run: |
        cd service-image-update-checkout
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add ${{ inputs.target-path }}
        git commit -am "update version ${{ inputs.image-version }} for service ${{ inputs.service }} " || true
        git push -u origin main
      shell: bash